# kubernetes/inference-service.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: housing-inference-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: housing-inference
  template:
    metadata:
      labels:
        app: housing-inference
    spec:
      containers:
      - name: housing-inference
        image: amibangladesh/housing-inference:latest
        ports:
        - containerPort: 8080
---
# apiVersion: v1
# kind: Service
# metadata:
#   name: housing-inference-service
# spec:
#   selector:
#     app: housing-inference
#   ports:
#   - protocol: TCP
#     port: 80
#     targetPort: 8080
#   type: LoadBalancer

apiVersion: v1
kind: Service
metadata:
  name: housing-inference-service
spec:
  type: NodePort
  selector:
    app: housing-inference
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30327
